version: "3.8"

services:
  kaffeefee:
    build: .
    ports:
      - 8080:8080
    environment: 
      DB: postgresql://kaffeefee:kaffeefee@db/kaffeefee?sslmode=disable
  db:
    image: postgres:13
    environment: 
      POSTGRES_PASSWORD: kaffeefee
      POSTGRES_USER: kaffeefee
      POSTGRES_DB: kaffeefee
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    